name: no-response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Run daily at midnight.
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          # Number of days of inactivity before an issue is closed for lack of response.
          daysUntilClose: 30
          responseRequiredLabel: waiting for author
